### ISSUE TITLE
Distinguishing between artifact ID types in GitBOM docs

### ISSUE THREAD

**Issue by edwarnicke** [omnibor/spec#15]
# Problem

There seems to be consensus around:

- [GitBOM SHA1/SHA256 parallel tree proposal](https://github.com/git-bom/spec/issues/9)

This means that there will be flavors of GitBOM documents that will vary by their gitoid hash type (gitoid:blob:sha1 vs gitoid:blob:sha256).

It would be useful to have a clean way to allow parsers to distinguish between GitBOM docs of different hash types.

# Possible Solutions

## Distinguish by Artifact ID Length
One could argue that you can simply distinguish between the document types by looking at the length of the hashes: sha1 is 40 hex characters and sha256 is 64 hex characters.  

### Pros:
1. ** Simple** - no explicit format change

### Cons:
1. **Inflexible** - Any future hash with the same length as an existing hash would be automatically unusable without changing the fundamental format.

## Distinguish by per Artifact ID URI

One other approach which could be taken would be to prefix each the appropriate URI scheme:

So:

```
blob⎵${artifact id}⎵bom⎵${GitBOM id}\n
```

would become:

```
blob⎵gitoid:blob:sha1:${artifact id}⎵bom⎵gitoid:blob:sha1:${GitBOM id}\n
```

### Cons
1. gitoid:blob:sha1 increases the overhead to file size due to repetition of information
3. Having each artifact id contain its own URI Scheme may encourage 'mixed hash' GitBOM files - something we have rejected as overly complex as part of the Dual tree approach.

## Distinguish by GitBOM Doc Header

Each GitBOM doc should begin with a line:

```
gitbom:${uri scheme of artifact id}:\n
```

For gitoid:blob:sha1 this would be:

```
gitbom:gitoid:blob:sha1:\n
```

### Pros
1. **Compact** - Scheme is expressed exactly once in a GitBOM document
3. **Flexible** - Can be used for any artifact id, including in the unforseeable future
4. **Magic string** - It is very useful to be able to tell if a given file is a GitBOM document.  By prepending line affirmatively identifying it as a gitbom of a particular artifact id type, it is easier for parsers to identify it as the file type they handle.

### Pro or Con (depending on perspective)
1.  **Single Artifact ID type per GitBOM Doc** - Only permits a single artifact ID type per GitBOM doc.

### Cons
1. **Complexity** - GitBOM documents go from being a simple array of input records to having a type header which slightly increases the complexity of the format.

**Comment by jsgf** [comment]
I like representations that cannot represent bad states. If we want all the hashes in a document to have all the same hash type, then the hash type should only be mentioned once. (That doesn't prevent it from referencing another doc of the wrong hash type, but one does what one can.)

**Comment by edwarnicke** [comment]
@jsgf I'm with you on making the right thing easy and the wrong thing hard (or impossible) :)

**Comment by alilleybrinker** [comment]
Closing, as I believe we did resolve this and update the spec accordingly.
