### ISSUE TITLE
Annex A comments

### ISSUE THREAD

**Issue by jsgf** [omnibor/spec#37]
> ${OMNIBOR_DIR}/objects/${Artifact Identifier Type uri prefix with ':' replaced by '_'}/${OmniBORID:0:2}/${OmniBORID:2:}

The two-digits/rest-of-digits technique for doing directory fanout has always bugged me. Why not do two-digits/all-digits just so that you can do, for example `find -name full-id` without having to muck about?

> .adg

This is very non-descript. Any 3 letter abbreviation is likely to conflict, and if you come across this with no context its hard to search (Art Directors Guild?). Why not `.omnibor`? I know there was previous discussion about `.gitbom` being confusing but that's moot now.

**Comment by edwarnicke** [comment]
> The two-digits/rest-of-digits technique for doing directory fanout has always bugged me. Why not do two-digits/all-digits just so that you can do, for example find -name full-id without having to muck about?

Interesting thought...

**Comment by edwarnicke** [comment]
> > .adg
> 
> This is very non-descript. Any 3 letter abbreviation is likely to conflict, and if you come across this with no context its hard to search (Art Directors Guild?). Why not `.omnibor`? I know there was previous discussion about `.gitbom` being confusing but that's moot now.

https://github.com/omnibor/spec/pull/50

**Comment by alilleybrinker** [comment]
Closing this as partially resolved, with the remaining consideration now tracked in #59.
