### ISSUE TITLE
OMNIBOR_DIR - location to store the omnibor documents

### ISSUE THREAD

**Issue by bharsesh** [omnibor/spec#39]
OMNIBOR_DIR specifies the location to store omnibor document.
The PR https://github.com/omnibor/spec/pull/35 discusses the order of precedence to set this variable. Some questions have come up during this review. 

1) Do we need a default OMNIBOR_DIR ? Default dir should be guaranteed to be writable.
- Should it be placed at the root of the project dir ?
- Should we have a global dir for the project and place the omnibor docs in one central place?
   Note that you need to know where to write to and where to read from.
- Should we place the omnibor documents along with the artifacts generated ? -- We could end up  
   with a scatter-gather problem 
- Need to be consistent. Build artifacts could go in one dir, omnibor docs could go into a different 
   dir. But beware of any overriding behaviour. 

2) Should the OMNIBOR_DIR be assumed to be write-only ?
Build pipelines will expect that the dir is write-only and it can be assumed to be never read from.

3) Can there be a collision ?
Two writers are not expected to write the same file. A tool is not expected to read and write at the same time (No stale reading expected)
- Can you read the omnibor docs when the file is being written (conflicts ?)
- Do you need to read the omnibor docs during build time ?
- Can we ensure Read After Write ?

4) It is difficult to get the right place to store the omnibor documents (by default).  So could we enforce this ? "If user doesn't specify where to put the omnibor stuff, then do not generate it". Note that the size of the data could potentially get huge (about 1G for kernel build). So user should have the option whether to generate it or not.

5) Some Guidelines for spec
- Need to have clear write boundaries in the spec: When can things be parallel, when should it be serial ?
- Consistency across languages, build tools : Call out edge cases in the spec Vs keep the spec abstract.
- End result should be decided so that it requires zero effort from an average developer.

**Comment by alilleybrinker** [comment]
Here is where I believe we stand on these questions:

### Do we need a default `OMNIBOR_DIR`?

No, there is no default `OMNIBOR_DIR`. Lack of an `OMNIBOR_DIR` is an indication to embed Artifact Input Manifests in the output binary or text file as described in Annex B and Annex C respectively.

### Should the `OMNIBOR_DIR` be assumed to be write-only?

I don't believe we've resolved this, nor extensively discussed it.

### Can there be a collision [ed: within the `OMNIBOR_DIR`]?

This and the sub-questions appear to be specifically about the consistency guarantees of the `OMNIBOR_DIR`. This probably deserves its own issue, as I don't believe it's been extensively discussed.

### Should we make the default for a lack of `OMNIBOR_DIR` be to not generated any separate files?

This is the default in the latest version of the spec.


---


Based on the above and partial resolution of the issues here, I'm going to close this and open a new issue for resolving consistency expectations for the `OMNIBOR_DIR`.
