### ISSUE TITLE
GitBOM SHA1/SHA256 parallel tree proposal

### ISSUE THREAD

**Issue by edwarnicke** [omnibor/spec#9]
# Problem

SHA1 has entered the inevitable stage of every hashes life where it is no-longer considered to be a strong hash.  While some may argue that the myths of its demise are overblown, the optics of its trustability are doubtless waning.

Git Object Ids are based on the Git Object Header and SHA1.  While arguments can be mounted about the relative strength of this vis-a-vis plain  SHA1, sufficient need has been seen for forward evolution that git now supports allowing a repo to be transitioned to sha256 based gitoids.  This transition has, thus far, been glacially slow, and there is no indication to date of it speeding up.

A big part of GitBOMs promise is the capacity to look up artifacts by the artifact ids provided.  Git Object Id transition to sha256 presents a challenge to that as there will inevitably be an extended period during which both sha1 and sha256 gitoids will be in common use.

# Proposal

Have build tools create, in parallel, gitoid:blob:sha1 and gitoid:blob:sha256 GitBOM Documents and embed them both into the resulting artifact (for example as a .bom:gitoid:blob:sha1  section and a .bom:gitoid:blob:sha256 section in an elf file).

**Comment by nellshamrell** [comment]
I agree with this approach - I've found that the mere mention of SHA1 (even though there is nuance to how it is being used) has immediately derailed or closed off conversations about GitBOM. Having both would at least show we are aware of the problems with sha1, but need to still support it for the time being, and are ready to progress to SHA256.

**Comment by alilleybrinker** [comment]
Closing, as we did reach a conclusion here for parallel trees and have updated the spec accordingly. If the conversation is ever reopened it's probably best to do so with a fresh issue which references this one.
